name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
        
    - uses: actions/checkout@v3
    - name: Build the Docker images
      run: |
        cd tiler 
        docker build . -t geodan/terraintiler
        cd ../warp
        docker build . -t geodan/terrainwarp

    - name: Publish the Docker images
      run: | 
         docker push geodan/terraintiler
         docker push geodan/terrainwarp
